### ISSUE TITLE
Ways to purge the Varnish cache?

### ISSUE THREAD

**Issue by aaronbushnell** [aelvan/VarnishPurge-Craft#2]
Hey, great work on this plugin! Just had a question about how the Varnish cache is purged. I think I understand this process, but wanted to make sure I was correct.

I understand this plugin can purge the Varnish cache in two ways:
1. It can purge the cache relevant to the saved entry/asset/element/etc. Similar to Craft purging content in  `{% cache %}` tags when an entry is saved.
2. Use [HTTP Headers to control the cache duration](https://github.com/aelvan/VarnishPurge-Craft#setting-http-headers-in-your-templates) at a page-level basis.

Is my understanding correct?

**Comment by aelvan** [comment]
Hi Aaron,

Well, you're at least touching on some important parts of it. :)

It's important to understand that 1) Varnish in itself is closely tied to the HTTP protocol, and 2) only caches based on URLs. By default it uses the HTTP cache headers in the backend response (from Craft) to set the TTL of the request. You can override this in the VCL, but I find it much more flexible to define this in my templates the way I describe in the documentation. 

If you set the the expiry time to one day in your HTTP headers, the cache will automatically be renewed one day after it was cached. This is how Varnish works, and doesn't have anything to do with the plugin per se.

So, when you want to purge something explicitly, before it expires, that can be done by sending a HTTP request to Varnish, with `PURGE` as the method, and passing in the url you want to purge. There are two ways the plugin can purge data. When an element (entry, category, asset, whatever) is saved in Craft, the url of that element (if it has one), will be purged. Also, if `varnishPurgeRelated` is set to `true`, the plugin will find all elements that have a relationship to the saved element (for instance, all entries that is using a specific asset), and purge all the urls of those elements.

This is similar to what Craft does, but not as precise. There are many cases where an element doesn't have a direct relationship to an url. For instance a page that lists the last twenty entries, or all entries in a category. That is done on the template level and not something that is stored in Craft. 

This is where the second way of purging helps, you can manually purge an elements url by selecting it in element indexes and using the element action that comes with the plugin.

Because of this it's smart to make unique pages in craft, instead of just using templates directly, when using this plugin and Varnish.

Hope that helps.

**Comment by aaronbushnell** [comment]
Thanks for the info, @aelvan! Appreciate you elaborating further on all this.
